In [ ]:
#variable
a = 10;
print('I am  ',a,'years old');

I am   10 years old


In [ ]:
a=int(input("enter a value"));
b=int(input("enter b value"));
print("Sum :",a+b)
print("product :",a*b)
print("Difference :",a-b)
print("Remainder :",a%b)
print("Division :",a/b)


enter a value5
enter b value3
Sum : 8
product : 15
Difference : 2
Remainder : 2
Division : 1.6666666666666667


In [ ]:
#Take a number from the user which is salary if the salary is more than 50,000 there is 10% tax print his final salary
sal=int(input("Enter your salary :"));
if(sal>=50000):
  tax=sal/10;
  print("Taxes are",tax)
  print("Your salary after taxes is  :",sal-tax)
else:
  print("Your salary is less than 50,000")
  print("No tax reduction for you")

Enter your salary :45000
Your salary is less than 50,000
No tax reduction for you


In [ ]:
#get the salary from the user if the salary is more than or equal to 50000 apply 10% tax reduction
#if the salary is less than 50000 apply 5%
#if the salary is more than 70000 apply 12% tax
#if the salary exceeds 1 lakh print you are promoted to next level
sal=int(input("Enter the salary :"))
if(sal<=50000):
  tax=0.05*sal;
  print("ur taxes are:",tax)
  print("ur final salary is:",sal-tax)
elif(sal>50000 and sal<=70000):
  tax=0.1*sal
  print("ur taxes are:",tax)
  print("ur final salary is:",sal-tax)
elif(sal>70000 and sal<100000):
  tax=0.12*sal
  print("ur taxes are:",tax)
  print("ur final salary is:",sal-tax)
else:
  print("You are promoted")






Enter the salary :0
ur taxes are: 0.0
ur final salary is: 0.0


In [ ]:
#for loop
n=int(input("enter n:"))
for i in range(1,11):
  print(n, 'x', i, '=', n*i)

enter n:999999999
999999999 x 1 = 999999999
999999999 x 2 = 1999999998
999999999 x 3 = 2999999997
999999999 x 4 = 3999999996
999999999 x 5 = 4999999995
999999999 x 6 = 5999999994
999999999 x 7 = 6999999993
999999999 x 8 = 7999999992
999999999 x 9 = 8999999991
999999999 x 10 = 9999999990


In [ ]:
#while loop
n=int(input("enter n value"))
i=1
while i<=10:
  print(n ,'x',i,'=',n*i)
  i+=1

enter n value1
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10


In [ ]:

#list
l1=[1,'d',5.66,False]#creating a list
l1.append("APPLE")#add elements at back of the list
l2=[1,2,3,]
l1.extend(l2)#l1=l1+l2

l1.pop(2)#removing values from the list
for i in l1:
  print(i)

1
d
False
APPLE


In [ ]:
l1.clear()
print(l1)

[]


In [ ]:
#create a list of 10integers elements
#print their squares
#save this squares in a new list
l1=[1,2,3,4,5,6,7,8,9,10]
l2=[]
for i in l1:
  n=i**2
  l2.append(n)
print(l2)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
l1=[1,2,3,4,5,6,7,8,9,10]
res=[i*i for i in l1 if i>5]
print(res)


[36, 49, 64, 81, 100]


In [ ]:
#lc
l1=[1,2,3,4,5,6,7,8,9]
res=[i*i if i>5 else "x" for i in l1]
print(res)

['x', 'x', 'x', 'x', 'x', 36, 49, 64, 81]


In [ ]:
#lc
salary=[78000,50400,34000,23000,14000]
res=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in salary]
print(res)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#dict
dict1 = {1:"prem",2:"venkat",3:"bala"}
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict[1])

{1: 'prem', 2: 'venkat', 3: 'bala'}
dict_keys([1, 2, 3])
dict_values(['prem', 'venkat', 'bala'])
dict[1]


In [ ]:
print(dict1[2])


venkat


In [ ]:
dict2={"dept":"cse","details":{"sec":"d","year":2}}
print("sec is",dict2["details"]["sec"])

sec is d


In [ ]:
#new zip
id1=[1,2,3,4]
names=["prem","venkat","r","e"]
new_dict=dict(zip(id1,names))
print(new_dict)

{1: 'prem', 2: 'venkat', 3: 'r', 4: 'e'}


In [ ]:
import numpy as np
A = np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,0]])#2d array
#element in each row = columns
print(a.ndim)
print(a.shape)
print(a)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 0]]


In [ ]:
import numpy as np
ar=np.array([[[1,2],[3,4],[5,6]],[[6,7],[5,4],[3,2]]])
print(ar.ndim)
print(ar.shape)
print(ar)

3
(2, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]

 [[6 7]
  [5 4]
  [3 2]]]


In [ ]:
A=np.ones((2,2,3))#creating  2 groups of array
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A=np.eye(2)#identity array
print(A)

[[1. 0.]
 [0. 1.]]


In [ ]:
A = np.arange(1,10,2)
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers divisible by 8 using arange func between 1-1000
a=np.arange(8,1001,8)
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [2]:
#spliting the range of numbers having common differences
import numpy as np
a=np.linspace(0,2,10)
print(a)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [8]:
#creating tuple
tuple=(1,2,3,"pspk",3.5)
print(tuple)

(1, 2, 3, 'pspk', 3.5)
(1, 2, 3, 'pspk', 3.5)


In [11]:
#tuple concat
t1=("p","r","e","m")
t2=("c","h","a","n","d","u")
print(t1+t2)#concatination


('p', 'r', 'e', 'm', 'c', 'h', 'a', 'n', 'd', 'u')


In [12]:
#tuple repitation
tuple=(1,2,3,"pspk",3.5)
print(tuple*5)


(1, 2, 3, 'pspk', 3.5, 1, 2, 3, 'pspk', 3.5, 1, 2, 3, 'pspk', 3.5, 1, 2, 3, 'pspk', 3.5, 1, 2, 3, 'pspk', 3.5)


In [15]:
#iteration
tuple=(1,2,3,"pspk",3.5)
for i in tuple:
 print(i)


1
2
3
pspk
3.5


In [10]:
tuple=(1,2,3,"pspk",3.5)
print(tuple)
print(tuple[-2])#slicing

(1, 2, 3, 'pspk', 3.5)
pspk


In [18]:
#membership operation
tuple=(1,2,3,"pspk",3.5)
print("pspk" in tuple)
print(5 in tuple)

True
False


In [20]:
t1=("p","r","e","m")
t2=("c","h","a","n","d","u")
print(t1 is not t2)

True


In [22]:
#creating set
set={1,2,3,5.6,"p"}
print(set)

{1, 2, 3, 5.6, 'p'}


set methods

In [23]:
#addition
s={2,3,5,6,7,8}
s.add(9)
print(s)

{2, 3, 5, 6, 7, 8, 9}


In [25]:
#update
s={2,3,5,6,7,8}
s.update({2,3,1})
print(s)

{1, 2, 3, 5, 6, 7, 8}


In [26]:
#poping any random element
s={2,3,5,6,7,8}
s.pop()
print(s)

{3, 5, 6, 7, 8}


In [29]:
#removing particular element
s={2,3,5,6,7,8}
s.remove(8)
print(s)

{2, 3, 5, 6, 7}


set operations

In [31]:
#union
s1={1,2,3}
s2={4,5,6}
print(s1.union(s2))

{1, 2, 3, 4, 5, 6}


In [33]:
#intersection
s1={1,2,3,4}
s2={4,5,6}
print(s1.intersection(s2))


{4}


In [36]:
#difference
s1={1,2,3}
s2={4,5,6}
print(s1.difference(s2))

{1, 2, 3}


In [37]:
 #superset
 s1={1,2,3,4,5,6}
s2={4,5,6}
print(s1.issuperset(s2))

True


In [39]:
#subset
s1={1,2,3,4,5,6}
s2={4,5,6}
print(s2.issubset(s1))

True
True
