In [ ]:
#sorting
a=[3,5,4,2,6]
b=sorted(a)
print(b)

[2, 3, 4, 5, 6]


In [ ]:
a=(3,5,4,2,6)
b=sorted(a)
print(b)

[2, 3, 4, 5, 6]


In [ ]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.linspace(2,10,12).reshape(3,4)
print(a)

[[ 2.          2.72727273  3.45454545  4.18181818]
 [ 4.90909091  5.63636364  6.36363636  7.09090909]
 [ 7.81818182  8.54545455  9.27272727 10.        ]]


In [ ]:
b=np.array([2,3,4,5])
b.resize(2,2)#changes the shape of original array
print(b)

[[2 3]
 [4 5]]


In [ ]:
#subtracting elements in array
a=np.array([2,3,4,5])
b=np.array([1,2,3,4])
c=a-b
print(a-b)


[1 1 1 1]


In [ ]:
#addinging elements in array
a=np.array([2,3,4,5])
b=np.array([1,2,3,4])
c=a+b
print(a+b)


[3 5 7 9]


In [ ]:
#one to one multiplication
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print(b)
c=a*b
print(c)


[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[ 2  6]
 [12 20]]


In [ ]:
#matrix multiplication
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print(b)
c=a@b
print(c)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[11 16]
 [19 28]]


In [ ]:
#matrix multiplication
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print("_______")
print(b)
c=a.dot(b)
print(c)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[11 16]
 [19 28]]


In [ ]:
a=np.array([1,2,3,4,5])
print(a.max())#max & min only accept numeric data types
print(a.min())

5


In [ ]:
a=np.array([2,3,4,5]).reshape(2,2)
print(a)
print('___________')#axis=0-column wise bigger num
print(a.max(axis=0))#axis=1-row wise bigger num
print("________")`
print(a.max(axis=1))




[[2 3]
 [4 5]]
___________
[4 5]
________
[3 5]


In [ ]:
#for min
a=np.array([2,3,4,5]).reshape(2,2)
print(a)
print('___________')#axis=0-column wise smaller num
print(a.min(axis=0))#axis=1-row wise smaller num
print("________")
print(a.min(axis=1))

[[2 3]
 [4 5]]
___________
[2 3]
________
[2 4]


In [ ]:
#joining arrays
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print("_______")
print(b)
print("after vertically stacking the array")
print(np.vstack((a,b)))


[[2 3]
 [4 5]]
_______
[[1 2]
 [3 4]]
after vertically stacking the array
[[2 3]
 [4 5]
 [1 2]
 [3 4]]


In [ ]:
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print("_______")
print(b)
print("after horigentally stacking the array")
print(np.hstack((a,b)))

[[2 3]
 [4 5]]
_______
[[1 2]
 [3 4]]
after horigentally stacking the array
[[2 3 1 2]
 [4 5 3 4]]


In [ ]:
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print("_______")
print(b)
print("after  stacking the array")
print(np.stack((a,b),axis=0))#joining arrays in vertically

[[2 3]
 [4 5]]
_______
[[1 2]
 [3 4]]
after  stacking the array
[[[2 3]
  [4 5]]

 [[1 2]
  [3 4]]]


In [ ]:
a=np.array([2,3,4,5]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a)
print("_______")
print(b)
print("after vertically stacking the array")
print(np.stack((a,b),axis=1))#joining arays in horigentally

[[2 3]
 [4 5]]
_______
[[1 2]
 [3 4]]
after vertically stacking the array
[[[2 3]
  [1 2]]

 [[4 5]
  [3 4]]]


In [ ]:
a=np.arange(10).reshape(2,1,5)
print(a)
print("after d stack")
print(np.dstack(a))#columns of each group will combine and covert  int rows

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
after d stack
[[[0 5]
  [1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [ ]:
#splitting arrays
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
print(np.vsplit(a,2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting
[array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.vsplit(a,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting")
np.hsplit(a,(3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
a.resize(3,6)
print(a)
print("after splitting")
np.hsplit(a,(2,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
a=np.array([4,3,5,6,7,8]).reshape(2,3)
print(a)
print(a.argmax())#finding the max element in matrix

[[4 3 5]
 [6 7 8]]
5


In [ ]:
a=np.array([4,3,5,6,7,8]).reshape(2,3)
print(a)
print(a.argmax(axis=0))#finding the max elements in column wise

[[4 3 5]
 [6 7 8]]
[1 1 1]


In [ ]:
a=np.array([4,3,5,6,7,8]).reshape(2,3)
print(a)
print(a.argmax(axis=1))#finding the max elements in row wise

[[4 3 5]
 [6 7 8]]
[2 2]


In [ ]:
a=np.array([4,3,5,6,7,8]).reshape(2,3)
print(a)
print(a.argmin(axis=0))#finding the min elements in column wise

[[4 3 5]
 [6 7 8]]
[0 0 0]


In [ ]:
a=np.array([2,4,3,5])
print("mean:",np.mean(a))
print("median:",np.median(a))
print("variance:",np.var(a))
print("standard dev:",np.std(a))

mean: 3.5
median: 3.5
variance: 1.25
standard dev: 1.118033988749895


trignometry

In [ ]:
a=np.pi
print(a)#radians

3.141592653589793


In [ ]:
np.rad2deg(a)

array([45., 60.])

In [ ]:
a=np.array([np.pi/4,np.pi/3])
print(a)

[0.78539816 1.04719755]


In [ ]:
a=np.array([0,30,45,60,90,120])
print(np.deg2rad(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951 ]
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301]


In [ ]:
np.arccos(1)#cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1m

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b))  #hypothese

7.211102550927978


In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(np.where(a==3))

(array([2]),)


In [12]:
a =np.array([1,5,2,3,9,])
b=sorted(a)
print(b)
print(np.searchsorted(b,2))

[1, 2, 3, 5, 9]
1


linear algebra and ufunc

In [18]:
a =np.array([1,25,6,3,9,])
b =np.array([1,5,2,3,9,])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.mod(a,b))
print(np.divide(a,b))
print(np.diff(a))
print(np.sort(a))

[ 2 30  8  6 18]
[ 0 20  4  0  0]
[0 0 0 0 0]
[1. 5. 3. 1. 1.]
[ 24 -19  -3   6]
[ 1  3  6  9 25]


In [22]:
a =np.array([1,25,6,3,9,])
b =np.array([1,5,2,3,9,])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[ 1  2  3  5  6  9 25]
[1 3 9]
[ 6 25]


In [24]:
a =np.trunc([-33.33,22.33])
print(a)


[-33.  22.]


In [25]:
b=np.fix([3.44])
print(b)

[3.]


In [27]:
c=np.around(3.445,2)
print(c)

3.44


In [31]:
a=np.array([3,4,56,78])
print(np.cumprod(a))

[    3    12   672 52416]


In [32]:
a=np.array([3,4,56,78])
print(np.cumsum(a))

[  3   7  63 141]


In [33]:
print(np.lcm(34,54))
print(np.gcd(5,45))

918
5


In [36]:
a=np.array([55,66,77])
print(np.lcm.reduce(a))
print(np.gcd.reduce(a))


2310
11


In [37]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [40]:
from numpy import random as rd
a=rd.rand(4)#default limit from 0 to 0.99
print(a)

[0.65649366 0.41424046 0.41002458 0.24805302]


In [39]:
a=rd.randint(5)#limit upto 4
print(a)

2


In [46]:
a=rd.randint(3)#limit upto 3
print(a)

1


joins

In [47]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(np.inner(a,b))#1x1+2X2+3X3

14


In [48]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(np.outer(a,b))#1x(1,2,3),2x(1,2,3),3x(1,2,3,)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [49]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(np.cross(a,b))

[0 0 0]
